version: "3.3"

services:
  varnish-mod:
    build:
      dockerfile: Dockerfile
      target: varnish_mod_dev
    user: root
    container_name: varnish-mod-dev
    command: tail -f /dev/null
    volumes: 
      - ./plugins/:/home/varnish/plugins
