#!/bin/sh
set -e

# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
varnishd \
   -F \
   -f /etc/varnish/default.vcl \
   -a http=:${VARNISH_HTTP_PORT:-80},HTTP \
   -a proxy=:${VARNISH_PROXY_PORT:-8443},PROXY \
   -p thread_pool_stack=256k \
   -p vsl_buffer=32k \
   -p feature=+http2 \
   -s malloc,$VARNISH_SIZE \
   "$@" &

exec "$@"

